# Generated by Django 5.0.2 on 2024-06-04 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartorder_cartorderitem_coupon_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlit',
            new_name='Wishlist',
        ),
    ]
