# Generated by Django 5.0.2 on 2024-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='video.mp4', null=True, upload_to='video_de_presentation')),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
