# Generated by Django 5.0.2 on 2024-06-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_presentation_user_presentation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=5, help_text='Numbers added here are in percentage e.g 5%')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Taxes',
                'ordering': ['country'],
            },
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='addrress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='order_statuts',
            new_name='order_status',
        ),
    ]
