# Generated by Django 5.0.2 on 2024-06-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_tax_rename_addrress_cartorder_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='tax_free',
            new_name='tax_fee',
        ),
    ]
