# Generated by Django 5.0.2 on 2024-07-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='tax_free',
            new_name='tax_fee',
        ),
    ]
