# Generated by Django 5.0.2 on 2024-07-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_tax_free_cartorderitem_tax_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tax_free',
            new_name='tax_fee',
        ),
    ]
