# Generated by Django 5.0.2 on 2024-07-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_tax_free_cart_tax_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Grand Total of all amount listed above', max_digits=12),
        ),
    ]
