# Generated by Django 5.0.2 on 2024-10-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_orb_features_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
