# Generated by Django 5.0.2 on 2024-11-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_color_color_code_alter_color_name_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='initial_total',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tax_fee',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='total',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('complete', 'Complete'), ('annule', 'Annule')], default='en_attente', max_length=100),
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
