# Generated by Django 5.0.2 on 2025-07-05 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_presentation_likes_comment'),
        ('vendor', '0005_alter_vendor_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='user',
        ),
        migrations.AddField(
            model_name='presentation',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
