# Generated by Django 5.2.4 on 2025-07-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_categoryinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order_item',
        ),
    ]
