# Generated by Django 5.2.4 on 2025-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_pushnotificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='solde',
            field=models.BooleanField(default=False),
        ),
    ]
