# Generated by Django 5.2.4 on 2025-12-04 18:58

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video',
            field=models.FileField(blank=True, default='video.mp4', null=True, upload_to='video_de_presentation', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'hevc', 'h265']), store.models.validate_video_size]),
        ),
    ]
