# Generated by Django 5.2.4 on 2026-04-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_presentation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='escrow_status',
            field=models.CharField(choices=[('pending_payment', 'En attente de paiement'), ('paid_holding', 'Payé – Fonds en séquestre'), ('shipped', 'Expédié par le vendeur'), ('validated', 'Réception validée par le client'), ('released', 'Fonds reversés au vendeur'), ('disputed', 'Litige ouvert'), ('refunded', 'Remboursé')], default='pending_payment', max_length=30),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='validation_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='vendor_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
