# Generated by Django 5.2.4 on 2026-04-26 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_vendor_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='store.category', verbose_name='Catégorie'),
        ),
    ]
