# Generated by Django 5.0.2 on 2024-11-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_follow'),
        ('vendor', '0002_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='vendor.vendor'),
        ),
    ]
