# Generated by Django 5.0.2 on 2024-11-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_follow_followed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
