# Generated by Django 5.0.2 on 2024-11-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_participants_to_user_and_vendor(apps, schema_editor):
    Conversation = apps.get_model('userauths', 'Conversation')
    Vendor = apps.get_model('vendor', 'Vendor')

    for conversation in Conversation.objects.all():
        # Assuming `participants` contains two entries: a user and a vendor's user
        participants = list(conversation.participants.all())
        if len(participants) == 2:
            # Assign the user and vendor based on roles
            user = participants[0] if not Vendor.objects.filter(user=participants[0]).exists() else participants[1]
            vendor = Vendor.objects.filter(user=participants[1]).first() or Vendor.objects.filter(user=participants[0]).first()
            
            conversation.user = user
            conversation.vendor = vendor
            conversation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_profile_phone_user_phone'),
        ('vendor', '0004_alter_vendor_followers'),
    ]

    operations = [
        # Add user field
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_conversations', to=settings.AUTH_USER_MODEL),
        ),
        # Add vendor field
        migrations.AddField(
            model_name='conversation',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_conversations', to='vendor.vendor'),
        ),
        # Data migration: Migrate participants data
        migrations.RunPython(migrate_participants_to_user_and_vendor, reverse_code=migrations.RunPython.noop),
        # Remove participants field
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        # Add unique_together constraint
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user', 'vendor')},
        ),
    ]
