# Generated by Django 5.0.2 on 2024-11-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_conversation_unique_together_conversation_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
