# Generated by Django 5.0.2 on 2024-11-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_conversation_unique_together'),
        ('vendor', '0004_alter_vendor_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user', 'vendor')},
        ),
    ]
