# Generated by Django 5.2.4 on 2026-04-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_user_reset_token_user_reset_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_view_users', models.BooleanField(default=True)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_ban_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('can_view_vendors', models.BooleanField(default=True)),
                ('can_approve_vendors', models.BooleanField(default=False)),
                ('can_suspend_vendors', models.BooleanField(default=False)),
                ('can_view_products', models.BooleanField(default=True)),
                ('can_edit_products', models.BooleanField(default=False)),
                ('can_delete_products', models.BooleanField(default=False)),
                ('can_feature_products', models.BooleanField(default=False)),
                ('can_view_orders', models.BooleanField(default=True)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_view_payments', models.BooleanField(default=False)),
                ('can_process_payouts', models.BooleanField(default=False)),
                ('can_view_stats', models.BooleanField(default=False)),
                ('can_manage_categories', models.BooleanField(default=False)),
                ('can_manage_presentations', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_admins', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle Admin',
                'verbose_name_plural': 'Rôles Admin',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.adminrole')),
            ],
            options={
                'verbose_name': 'Profil Admin',
                'verbose_name_plural': 'Profils Admin',
            },
        ),
    ]
